languageCode = "de-de"
title = "AntMe! Dokumentation"
RelativeUrls = true
uglyurls = true
theme = "AntMe"
DefaultContentLanguage = "de"
sectionPagesMenu = "nav"
publishDir = "docs"
pluralizelisttitles= "false"
disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
  [languages.de]
    title = "AntMe! Dokumentation"
    languageName = "Deutsch"
    contentDir = "content/de"
    weight = 1
  [languages.en]
    title = "AntMe! Documentation"
    languageName = "English"
    contentDir = "content/en"
    weight = 2


[menu]
  [[menu.nav]]
    name = "Home"
    url = "/index.html"
    weight = 1


[markup]
  [markup.highlight]
    codeFences = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4